class _BotCommands:
    def __init__(self):
        self.StartCommand = 'start'
<<<<<<< HEAD
        self.MirrorCommand = 'm'
        self.UnzipMirrorCommand = 'unpack'
        self.TarMirrorCommand = 'tar'
        self.ZipMirrorCommand = 'zip'
        self.CancelMirror = 'cancel'
        self.CancelAllCommand = 'cancelall'
        self.ListCommand = 'cari'
=======
        self.MirrorCommand = 'mirror'
        self.UnzipMirrorCommand = 'unzipmirror'
        self.ZipMirrorCommand = 'zipmirror'
        self.CancelMirror = 'cancel'
        self.CancelAllCommand = 'cancelall'
        self.ListCommand = 'list'
        self.SearchCommand = 'search'
>>>>>>> 2aaacf0bec6285ef29ff9bbb699762804dca37c9
        self.StatusCommand = 'status'
        self.AuthorizedUsersCommand = 'users'
        self.AuthorizeCommand = 'authorize'
        self.UnAuthorizeCommand = 'unauthorize'
        self.AddSudoCommand = 'addsudo'
        self.RmSudoCommand = 'rmsudo'
        self.PingCommand = 'ping'
        self.RestartCommand = 'restart'
<<<<<<< HEAD
        self.StatsCommand = 'specs'
        self.HelpCommand = 'help'
        self.LogCommand = 'log'
        self.SpeedCommand = 'speedtest'
        self.CloneCommand = 'c'
        self.CountCommand = 'count'
        self.WatchCommand = 'w'
        self.TarWatchCommand = 'tarw'
        self.ZipWatchCommand = 'zipw'
        self.QbMirrorCommand = 'qb'
        self.QbUnzipMirrorCommand = 'qbunpack'
        self.QbTarMirrorCommand = 'qbtar'
        self.QbZipMirrorCommand = 'qbzip'
        self.DeleteCommand = 'delt'
        self.ShellCommand = 'shell'
        self.ExecHelpCommand = 'exechelp'
        self.TsHelpCommand = 'tshelp'
        self.LeechSetCommand = 'leechset'
        self.SetThumbCommand = 'setthumb'
        self.LeechCommand = 'leech'
        self.TarLeechCommand = 'tarleech'
        self.UnzipLeechCommand = 'unzipleech'
        self.ZipLeechCommand = 'zipleech'
        self.QbLeechCommand = 'qbleech'
        self.QbTarLeechCommand = 'qbtarleech'
        self.QbUnzipLeechCommand = 'qbunzipleech'
        self.QbZipLeechCommand = 'qbzipleech'
        self.LeechWatchCommand = 'leechwatch'
        self.LeechTarWatchCommand = 'leechtarwatch'
        self.LeechZipWatchCommand = 'leechzipwatch'
=======
        self.StatsCommand = 'stats'
        self.HelpCommand = 'help'
        self.LogCommand = 'log'
        self.SpeedCommand = 'speedtest'
        self.CloneCommand = 'clone'
        self.CountCommand = 'count'
        self.WatchCommand = 'watch'
        self.ZipWatchCommand = 'zipwatch'
        self.QbMirrorCommand = 'qbmirror'
        self.QbUnzipMirrorCommand = 'qbunzipmirror'
        self.QbZipMirrorCommand = 'qbzipmirror'
        self.DeleteCommand = 'del'
        self.ShellCommand = 'shell'
        self.ExecHelpCommand = 'exechelp'
        self.LeechSetCommand = 'leechset'
        self.SetThumbCommand = 'setthumb'
        self.LeechCommand = 'leech'
        self.UnzipLeechCommand = 'unzipleech'
        self.ZipLeechCommand = 'zipleech'
        self.QbLeechCommand = 'qbleech'
        self.QbUnzipLeechCommand = 'qbunzipleech'
        self.QbZipLeechCommand = 'qbzipleech'
        self.LeechWatchCommand = 'leechwatch'
        self.LeechZipWatchCommand = 'leechzipwatch'
        self.RssListCommand = 'rsslist'
        self.RssGetCommand = 'rssget'
        self.RssSubCommand = 'rsssub'
        self.RssUnSubCommand = 'rssunsub'
        self.RssUnSubAllCommand = 'rssunsuball'
>>>>>>> 2aaacf0bec6285ef29ff9bbb699762804dca37c9

BotCommands = _BotCommands()
